export const GET_USER_LOCAL_STORAGE = 'GET_USER_LOCAL_STORAGE'
export const SET_USER_LOCAL_STORAGE = 'SET_USER_LOCAL_STORAGE'
export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_INVITATIONS = 'GET_USER_INVITATIONS'
