export const HOME = '/'
export const LOGIN = '/login'
export const RESTRICTED_AREA = '/restrictedArea'
export const NOT_AUTHORIZED = '/notAuthorized'
export const FORGOT_PASSWORD = '/forgotPassword'

export const ADM_DASHBOARD = '/admin/dashboard'
export const ADM_USERS = '/admin/users'
export const ADM_ORDERS = '/admin/orders'
export const ADM_BOOKS = '/admin/books'
