export const HOME = '/'
export const LOGIN = '/login'
export const RESTRICTED_AREA = '/restrictedArea'
export const FORGOT_PASSWORD = '/forgotPassword'
export const NOVEL = '/novel'
export const DASHBOARD = '/dashboard'
